### ISSUE TITLE
Text decoration

### ISSUE THREAD

**Issue by dzehnder** [hlxsites/mammotome#101]
Items:
- [ ] Be able to change text size
- [ ] Be able to center text in a section

Most pages have a pretty big font size, we could change the default font size to this, and add a section metadata for the exceptions, where they are smaller.

A lot of sections also have their text centered, but some others don't. One of them needs to be the default, but the behavior should be changed in the section metadata.

Mostly like this:
![Screenshot 2023-05-04 at 17 42 13](https://user-images.githubusercontent.com/16799758/236258839-cb4e604c-81b5-4e9c-bdf6-89475d56b6e5.png)

Sometimes like this:
![Screenshot 2023-05-04 at 17 42 29](https://user-images.githubusercontent.com/16799758/236258909-4b9998b9-0401-435c-97c6-d529db1998de.png)

**Comment by Acidham** [comment]
@dzehnder I think the first example makes total sense in case default content is entered and allowing the user to custom the font size of a `p` but the second example is part of each individual block and the implementation of such. 

I suggest to impl. Style Metadata for font-size and alignment. 

E.g. 
`font-size-s`, `font-size-m`, etc and `center`

thoughts?

**Comment by Acidham** [comment]
#133
