### ISSUE TITLE
Language Navigation

### ISSUE THREAD

**Issue by solaris007** [hlxsites/mammotome#16]
Add language navigation.
![Screenshot 2023-03-15 at 11 33 05](https://user-images.githubusercontent.com/1872195/225283131-12756a43-b314-4c85-9af1-28ec47cb515b.png)

- link to same page in other language
- clarify with customer which equivalent page linking option to use (should guide towards option 1): we use the english paths / page names for all languages (confirm with customer) - options are documented here: https://github.com/hlxsites/elco-aerotop-sg/issues/35#issuecomment-1401575322

Out of scope:
- Korean and Chinese languages
- removing a language if there is no corresponding page in the other language

**Comment by chicharr** [comment]
I take this issue for me. I can't assign it in github at the moment.

**Comment by solaris007** [comment]
already implemented as part of https://github.com/hlxsites/mammotome/pull/30

**Comment by solaris007** [comment]
visually language navigation is added via https://github.com/hlxsites/mammotome/pull/30

the business logic remains to be implemented as per spec
