### ISSUE TITLE
List style

### ISSUE THREAD

**Issue by dzehnder** [hlxsites/mammotome#171]
Global style for lists:
<img width="993" alt="Screenshot 2023-05-31 at 11 14 01" src="https://github.com/hlxsites/mammotome/assets/16799758/57f7e197-12f6-4c06-b51b-6c97e97d3604">

Column list style:
<img width="410" alt="Screenshot 2023-05-31 at 11 14 56" src="https://github.com/hlxsites/mammotome/assets/16799758/246671db-59a9-4597-af24-f278cb5c86a7">

**Comment by Acidham** [comment]
Should be fixed with #168
