### ISSUE TITLE
Add option to the collapsible block so that it is positioned in the center of the page

### ISSUE THREAD

**Issue by smiroslav** [hlxsites/mammotome#179]
Using block-level style attribute following should be achieved
- [ ] position block content in the center of the page
- [ ] the width of the block should have an upper limit (check exact value in the page below)

https://www.mammotome.com/patient-resources/faqs-about-the-devices/

**Comment by Acidham** [comment]
@smiroslav we discussed adding the ability to add an option for NARROW version (610px) or full size. I am uncertain if the option is required. Please follow up with the customer if wide version is also required and implement accordingly.

**Comment by meryllblanchet** [comment]
Closing as not requested by the customer.
