### ISSUE TITLE
Cards links

### ISSUE THREAD

**Issue by dzehnder** [hlxsites/mammotome#182]
There should be an option to add a link to whole cards (not only to the text within the cards).
A lot of pages have cards, some with images and some without, that link to other pages. In those cases, the entiere card should be the link.

Example pages:
https://www.mammotome.com/patient-resources/
https://www.mammotome.com/news-media/
https://www.mammotome.com/product-support/

This could be achieved by adding another column to the cards block containing the link

**Comment by smiroslav** [comment]
That is already supported
https://main--mammotome--hlxsites.hlx.page/en/products/cards-test-wide-no-callout
