### ISSUE TITLE
Styling for Video

### ISSUE THREAD

**Issue by krizel4** [hlxsites/mammotome#221]
Original: https://www.mammotome.com/portfolios/magnetic-lesion-localization/
Franklin: https://main--mammotome--hlxsites.hlx.page/us/en/portfolios/magnetic-lesion-localization

H2 Styling doesn't match.

**Comment by Acidham** [comment]
@krizel4 can you please provide a screenshot with the not matching H2?

Just drag&drop the file here.

**Comment by krizel4** [comment]
Here's the screenshot. It's located at: https://www.mammotome.com/portfolios/magnetic-lesion-localization/![image](https://github.com/hlxsites/mammotome/assets/55035633/784f7c82-a296-480b-aafe-a89cb381f576)
