### ISSUE TITLE
Style: space between header and columns block

### ISSUE THREAD

**Issue by Acidham** [hlxsites/mammotome#246]
The space between the header and columns block needs to be smaller.

![Screenshot 2023-06-14 at 12 32 17](https://github.com/hlxsites/mammotome/assets/17712121/2da5f0c1-2279-46aa-b19a-fe72a7b90015)

**Comment by dzehnder** [comment]
Looks like this has already been resolved
![Screenshot 2023-06-28 at 16 55 00](https://github.com/hlxsites/mammotome/assets/16799758/b41482a6-76bc-4b4b-9b3b-9fed740f553a)

**Comment by Acidham** [comment]
Yes with spacer approach, it can be resolved in word.
