### ISSUE TITLE
Style: Video Block

### ISSUE THREAD

**Issue by Acidham** [hlxsites/mammotome#247]
* [ ] Padding bottom between Video Block and Callout missing; Video Block flows over Callout
* [ ] Padding with the blue box. The Header and Video needs to be more centered.
* [ ] Size of the blue box, smaller than originally

![Screenshot 2023-06-14 at 12 38 09](https://github.com/hlxsites/mammotome/assets/17712121/a4474aa1-40b7-48db-b97e-675f6e5b043b)

**Comment by dzehnder** [comment]
Looks like this might have already been resolved:
![Screenshot 2023-06-28 at 16 53 02](https://github.com/hlxsites/mammotome/assets/16799758/82fd735e-0bfc-4f98-b31a-79fa38c2439b)
