### ISSUE TITLE
Video Player

### ISSUE THREAD

**Issue by solaris007** [hlxsites/mammotome#25]
Add video player. This could be done with auto-blocking, i.e. by embedding the video player when encountering a-tags with a youtube source.

Should have features:
- youtube source
- can be used independently or  in columns / other blocks
- can be on the same page multiple times
- thumbnail image
- overlayed play button
- after clicking, video features as per original site

Mobile (here multiple on same page):
![Screenshot 2023-03-17 at 11 35 26](https://user-images.githubusercontent.com/1872195/225881217-6bdaf279-fd60-4a6b-b380-3526bbbd6f1a.png)

Desktop (here multiple on same page):
![Screenshot 2023-03-17 at 11 36 02](https://user-images.githubusercontent.com/1872195/225881440-c4ca2ed3-d897-4a37-bc55-fbfee3621823.png)

![Screenshot 2023-03-17 at 11 40 07](https://user-images.githubusercontent.com/1872195/225882296-cd1fbf39-b029-41cf-b053-b2638e5d37f9.png)

Inspirations:
- https://github.com/hlxsites/elco-aerotop-sg/tree/main/blocks/youtube-player
- https://github.com/adobe/helix-block-collection/tree/main/blocks/video

**Comment by Acidham** [comment]
<img width="1070" alt="Screenshot 2023-03-28 at 08 09 30" src="https://user-images.githubusercontent.com/17712121/228144583-98817a7a-235c-46b9-82d9-8f6cfddd2159.png">

**Comment by solaris007** [comment]
@Acidham yes that's just a side effect of me having uploaded thumbnails of different aspect ratio in the content. an author would fix that by using same-sized images everywhere.
