### ISSUE TITLE
Style: Cards in mobile view

### ISSUE THREAD

**Issue by Acidham** [hlxsites/mammotome#262]
Wrong text alignment and size of Cards (three-columns) in the mobile version:

![Screenshot 2023-06-15 at 11 32 02](https://github.com/hlxsites/mammotome/assets/17712121/d5f9565b-a49a-45c4-b8f8-9439680a6b90)

mammotome.com
![Screenshot 2023-06-15 at 11 32 33](https://github.com/hlxsites/mammotome/assets/17712121/e4095b60-8cb5-437b-82d0-6c9d5b9c378d)

**Comment by chicharr** [comment]
Hi @dzehnder 
not sure if I'm looking at the right place, but it looks like the height of the cards, and font are still different in your PR from the ones in mammotome.com. Was it agreed with the customer to change the appearance?

Your PR:
![Screenshot 2023-06-19 at 15 28 23](https://github.com/hlxsites/mammotome/assets/43381734/ea3528e3-cf64-41c6-9619-4cdc7571e754)

Mammotome.com
![Screenshot 2023-06-19 at 15 28 31](https://github.com/hlxsites/mammotome/assets/43381734/5fa01351-30cd-4797-ab98-fdfc9ef6368a)
