### ISSUE TITLE
Style: Cards image is clipped

### ISSUE THREAD

**Issue by karlpauls** [hlxsites/mammotome#263]
In the original page, the image of cards is not clipped:

<img width="1432" alt="Bildschirm­foto 2023-06-15 um 11 39 01" src="https://github.com/hlxsites/mammotome/assets/410610/4d77f78d-846d-440c-a464-50a7ce631518">

while in our version it is (because it is set to `cover` instead of `contains`):

<img width="1432" alt="Bildschirm­foto 2023-06-15 um 11 40 06" src="https://github.com/hlxsites/mammotome/assets/410610/a472cecc-2231-46ef-8c28-b9a4e0739e9d">

**Comment by dzehnder** [comment]
fixed in #354
