### ISSUE TITLE
Style: Product Support + Card Buttons

### ISSUE THREAD

**Issue by krizel4** [hlxsites/mammotome#275]
Ref: Card buttons towards the bottom of the main page and on product support (https://main--mammotome--hlxsites.hlx.page/us/en/product-support)

- In mobile, the text doesn't vertically align. It floats to the top. 

For Product Support:
- Size of the card buttons should be similar to what appears on the main page.
- The designers prefer the blue overlay over the header
- Header should be the same height as the pages that appear under the portfolio pages.

**Comment by Acidham** [comment]
We just merged it today: https://main--mammotome--hlxsites.hlx.page/us/en/product-support

**Comment by krizel4** [comment]
Looks good. Thank you!
