### ISSUE TITLE
Nav glitch?

### ISSUE THREAD

**Issue by krizel4** [hlxsites/mammotome#286]
Every now and then on desktop, mobile and tablet, the Nav bar appears and then doesn't appear. 

https://main--mammotome--hlxsites.hlx.page/us/en/portfolios/gamma-detection

![image](https://github.com/hlxsites/mammotome/assets/55035633/0861b80f-1fda-40a9-b777-369ec2c6e614)

**Comment by Acidham** [comment]
This happened due to a test section metadata in the Word doc. I removed the table and nav is shown properly.
