### ISSUE TITLE
About us pages discrepancies

### ISSUE THREAD

**Issue by krizel4** [hlxsites/mammotome#296]
Different style needed for "25 years of breast care innovation." 

Call to action footer should be smaller. 

![image](https://github.com/hlxsites/mammotome/assets/55035633/9c6b51c6-8741-48de-89ee-9a8d0c6309b7) 

![image](https://github.com/hlxsites/mammotome/assets/55035633/2990386f-64ef-4897-935c-ce3f935655ac)

**Comment by Acidham** [comment]
1. changed word file with the correct formatting.
2. "Celebrating 25 years of innovation" follows a down-sizing rule for H1. On other pages, H1 gets downsized, and therefore it applies to the about us page as well (re. consitency)

Please review....

**Comment by krizel4** [comment]
Looks good. Thank you!
