### ISSUE TITLE
Podcasts Page: Image and Title Alignment

### ISSUE THREAD

**Issue by kelseywilliams751** [hlxsites/mammotome#304]
The title of the podcast should be left aligned with the second paragraph instead of pushed to the right. The podcast titles should also be 500 weight.

<img width="1353" alt="Screenshot 2023-06-20 at 9 51 56 AM" src="https://github.com/hlxsites/mammotome/assets/110261213/26f937df-abe4-4ba1-a7a4-99e47fb5f87a">

**Comment by smiroslav** [comment]
https://main--mammotome--hlxsites.hlx.page/us/en/about-us/news-media-category/podcasts

**Comment by krizel4** [comment]
Green light from Kelsey and I!

**Comment by kelseywilliams751** [comment]
That change looks great! Thank you!
