### ISSUE TITLE
Mammotome One Voice Podcast Page Discrepancies

### ISSUE THREAD

**Issue by kelseywilliams751** [hlxsites/mammotome#305]
The purple Join the Conversation section towards the bottom has many discrepancies with the live site. The Mammotome Cares logo image is too big. The "@MammotomeCares on Facebook" text needs to be bigger and white so it's easier to read.

Hlx Site:
<img width="1353" alt="Screenshot 2023-06-20 at 10 06 36 AM" src="https://github.com/hlxsites/mammotome/assets/110261213/50a2ea46-5fe5-4b66-b91c-95f3dc9b3e49">

Mammotome Live Site:
<img width="1353" alt="Screenshot 2023-06-20 at 10 06 53 AM" src="https://github.com/hlxsites/mammotome/assets/110261213/59550ac7-7ee8-485e-9b2d-866f49bb1d71">

**Comment by smiroslav** [comment]
https://main--mammotome--hlxsites.hlx.page/us/en/about-us/news-media-category/mammotome-one-voice

**Comment by smiroslav** [comment]
@kelseywilliams751 I have made changes in the code, and can be seen on the page below 
https://305-column-enhancement--mammotome--hlxsites.hlx.page/us/en/about-us/news-media-category/mammotome-one-voice
