### ISSUE TITLE
Style: Form

### ISSUE THREAD

**Issue by krizel4** [hlxsites/mammotome#311]
https://main--mammotome--hlxsites.hlx.page/us/en/contact/
https://main--mammotome--hlxsites.hlx.page/us/en/schedule-a-demo

- Missing the logo background
- Make sure all text is the same color: #6D6E71
- Contact Type field should flush left with the fields
- Message field should occupy the entire width of the form. 
- Placeholder text for the message field should be Roboto
- Increase the "Products" column width
- Consent language: Reduce font and line-height
- Opt-in fields row should occupy the full-width of the form
- "Submit" button should be rounded

**Comment by Pareesh** [comment]
Hi @krizel4 ,
We have done some improvement with changes https://github.com/hlxsites/mammotome/pull/162 , Kindly please. re-verify the forms and let me know if any of the above bugs persists.

Thank you

**Comment by Pareesh** [comment]
Hi @krizel4 ,
Kindly please verify with 
https://313-mammotomoe--mammotome--hlxsites.hlx.page/us/en/schedule-a-demo and 
https://313-mammotomoe--mammotome--hlxsites.hlx.page/us/en/contact/

Thank you

**Comment by solaris007** [comment]
@krizel4 no feedback within 2 weeks, closing as silent consensus.. feel free to re-open if issue seems unresolved to you.
