### ISSUE TITLE
style: 2 column video

### ISSUE THREAD

**Issue by krizel4** [hlxsites/mammotome#327]
We need 2 column styling option for videos:

Ref: https://www.mammotome.com/products/mammotome-confirm/

**Comment by karlpauls** [comment]
@krizel4, I double checked and we actually already support 2 column styling for videos. Just needs a `(two columns)` added to the `Videos` block. I just wasn't aware of that during the call - we will document the block in the docs. Thanks for reporting - I added the `(two columns)` option to the Mammotome confirm page already.
