### ISSUE TITLE
New block request for products

### ISSUE THREAD

**Issue by krizel4** [hlxsites/mammotome#328]
Page ref: https://www.mammotome.com/products/mammotome-confirm/

Please refer to the section with the text "Would you like to know more about the Mammotome Confirm™ system?"

The height should be flexible and image size reduced. When it's section metadata, the height of the area is maxed and cuts off content. The image is also oversized.

Most of the other product pages have this as a section as well.

**Comment by Acidham** [comment]
@krizel4 I think it would make sense to implement a Callout block. For the moment, we can use this block for the product pages. Post-Go live, we can think about enhancing the block to cover the arc version as well. Thoughts?

**Comment by krizel4** [comment]
Not sure if changes were made, but it actually looks fine now!  I told Jean-Claude that when we were creating this block during our call, the image was large and instead of the image auto-sizing within the block, it maintained its original size and the top and bottom of the image was cut off. Also, because the image was so large the text and button below it was cut off as well.
