### ISSUE TITLE
Form Support

### ISSUE THREAD

**Issue by solaris007** [hlxsites/mammotome#33]
Current forms on the original site:

- Contact Form (https://en-gb.mammotome.com/contact/)
- Submission Form (https://www.mammotome.com/contact/innovate-with-mammotome/)
- Study Request Form including File Upload (https://www.mammotome.com/contact/investigator-initiated-study-request/)
- Schedule a Demo Form (https://www.mammotome.com/schedule-a-demo/)
- Tech Support Ticket Form including file upload (https://www.mammotome.com/submit-a-tech-support-ticket/)

Franklin forms documentation: https://www.hlx.live/developer/forms

Some forms use file upload. How to handle this is as of yet undecided. Research as part of this ticket.

**Comment by jalagari** [comment]
o	[Contact Us](https://33-forms--mammotome--hlxsites.hlx.page/en/contact/) 
o	[Innovate Form](https://33-forms--mammotome--hlxsites.hlx.page/en/contact/innovate-with-mammotome/)
o	[Study Request](https://33-forms--mammotome--hlxsites.hlx.page/en/contact/investigator-initiated-study-request/)
o	[Schedule Demo](https://33-forms--mammotome--hlxsites.hlx.page/en/schedule-a-demo/) 
o	[Tech Support Ticket](https://33-forms--mammotome--hlxsites.hlx.page/en/submit-a-tech-support-ticket/)

**Comment by jalagari** [comment]
Forms Urls are changed 


https://main--mammotome--hlxsites.hlx.page/en/submit-a-tech-support-ticket
https://main--mammotome--hlxsites.hlx.page/en/schedule-a-demo
https://main--mammotome--hlxsites.hlx.page/en/contact/
https://main--mammotome--hlxsites.hlx.page/en/about-us/investigator-initiated-study-request
https://main--mammotome--hlxsites.hlx.page/en/about-us/innovate-with-mammotome
