### ISSUE TITLE
Paragraph Line Heights

### ISSUE THREAD

**Issue by kelseywilliams751** [hlxsites/mammotome#336]
Can we set a default line height for paragraphs to 1.5 rem. Currently paragraphs are displaying with a 2.5 rem line height that is too big.

Example:
https://main--mammotome--hlxsites.hlx.page/us/en/hospital-marketing-kit-preview
![Screenshot 2023-06-23 at 2 18 58 PM](https://github.com/hlxsites/mammotome/assets/110261213/32d274d1-53d1-4355-a2ab-b1c9e7feff8a)

**Comment by Acidham** [comment]
@kelseywilliams751 I assume this should be applied to normal text with font-size 16px?

**Comment by kelseywilliams751** [comment]
Yes, just for normal text. Thanks!
