### ISSUE TITLE
US/EN content import

### ISSUE THREAD

**Issue by karlpauls** [hlxsites/mammotome#338]
We need to import the following urls (note, some are already there but need to be checked for completeness):

- [x] https://www.mammotome.com/about-us/
- [x] https://www.mammotome.com/about-us/locations/
- [x] https://www.mammotome.com/about-us/our-culture/
- [x] https://www.mammotome.com/about-us/our-history/
- [x] https://www.mammotome.com/about-us/team/
- [x] https://www.mammotome.com/agreement-and-release-for-unsolicited-submission/
- [x] https://www.mammotome.com/california-consumer-privacy-act/
- [x] https://www.mammotome.com/canada-product-catalog/ (found here: https://main--mammotome--hlxsites.hlx.page/us/en/products/catalog-canada)
- [x] https://www.mammotome.com/confirm-submission/ (found here: https://main--mammotome--hlxsites.hlx.live/us/en/thank-you/)
- [x] https://www.mammotome.com/contact/
- [x] https://www.mammotome.com/contact/elementor-16435/ (FALSE POSITIVE)
- [x] https://www.mammotome.com/contact/innovate-with-mammotome/
- [x] https://www.mammotome.com/contact/investigator-initiated-study-request/
- [x] https://www.mammotome.com/copyright-trademark/
- [x] https://www.mammotome.com/demo-thank-you/ (same as normal thank you - found here: https://main--mammotome--hlxsites.hlx.live/us/en/thank-you/)
- [x] https://www.mammotome.com/devicor-patent-marking/
- [x] https://www.mammotome.com/french-canadian-product-catalog/ (found here: https://main--mammotome--hlxsites.hlx.page/us/en/products/catalog-french-canada)
- [x] https://www.mammotome.com/healthcare-professionals/
- [x] https://www.mammotome.com/healthcare-professionals-category/clinical-evidence/
- [x] https://www.mammotome.com/healthcare-professionals-category/partner-with-mammotome/ (Placeholder page: SKIP)
- [x] https://www.mammotome.com/healthcare-professionals-category/seminars/
- [x] https://www.mammotome.com/healthcare-professionals-category/studies/ (Placeholder page: SKIP)
- [x] https://www.mammotome.com/healthcare-professionals-category/tradeshow-events/
- [x] https://www.mammotome.com/healthcare-professionals-category/webinars/
- [x] https://www.mammotome.com/healthcare-professionals/placeholder-for-menus-and-categories/  (Placeholder page: SKIP)
- [x] https://www.mammotome.com/hospital-marketing-kit-downloadable-assets/ (SKIP as not linked)
- [x] https://www.mammotome.com/hospital-marketing-kit-preview/ (SKIP as not linked)
- [x] https://www.mammotome.com/ifu-index/
- [x] https://www.mammotome.com/legal-imprint/ (placeholder page: SKIP)
- [x] https://www.mammotome.com/mammocare-service-agreement/
- [x] https://www.mammotome.com/news-media-category/careers-blog/
- [x] https://www.mammotome.com/news-media-category/news-mentions/
- [x] https://www.mammotome.com/news-media-category/news/
- [x] https://www.mammotome.com/news-media-category/podcasts/
- [x] https://www.mammotome.com/news-media-category/press-releases/
- [x] https://www.mammotome.com/news-media/a-culture-of-continuous-improvement/
- [x] https://www.mammotome.com/news-media/baptist-health-offering-new-tech-for-breast-cancer-patients/
- [x] https://www.mammotome.com/news-media/careers-blog-aspire-to-inspire/
- [x] https://www.mammotome.com/news-media/careers-blog-interviewing-at-mammotome/
- [x] https://www.mammotome.com/news-media/from-clinical-to-corporate/
- [x] https://www.mammotome.com/news-media/mammotome-25/
- [x] https://www.mammotome.com/news-media/mammotome-announces-the-launch-of-the-mammotome-dualcore-dual-stage-core-biopsy-system/
- [x] https://www.mammotome.com/news-media/mammotome-associates-thoughts-on-womens-history-month
- [x] https://www.mammotome.com/news-media/mammotome-one-voice/
- [x] https://www.mammotome.com/news-media/news-press-release-flexible-hydromark/
- [x] https://www.mammotome.com/news-media/nuvance-health-offer-breast-cancer-technique-that-reduces-side-effects-from-surgery/
- [x] https://www.mammotome.com/news-media/taking-pride-in-mammotomes-d-i-efforts
- [x] https://www.mammotome.com/news-media/the-magtrace-lympathic-tracer-offers-a-new-option-for-assessing-dcis/
- [x] https://www.mammotome.com/news-media/transitioning-from-the-military-to-a-civilian-career/
- [x] https://www.mammotome.com/news-media/work-life-balance-at-mammotome/
- [x] https://www.mammotome.com/online-terms-of-use/
- [x] https://www.mammotome.com/patient-resources/
- [x] https://www.mammotome.com/patient-resources-category/breast-biopsy/
- [x] https://www.mammotome.com/patient-resources-category/breast-care/
- [x] https://www.mammotome.com/patient-resources-category/mammotome-biopsy-devices/
- [x] https://www.mammotome.com/patient-resources-category/understanding-biopsy-results/
- [x] https://www.mammotome.com/patient-resources-category/webinars/
- [x] https://www.mammotome.com/patient-resources/benign-diagnosis/
- [x] https://www.mammotome.com/patient-resources/breast-biopsy-modalities/
- [x] https://www.mammotome.com/patient-resources/breast-cancer-myths/
- [x] https://www.mammotome.com/patient-resources/facts-about-the-devices/
- [x] https://www.mammotome.com/patient-resources/faqs-about-the-devices/
- [x] https://www.mammotome.com/patient-resources/fibroadenomas/
- [x] https://www.mammotome.com/patient-resources/how-they-work/
- [x] https://www.mammotome.com/patient-resources/if-its-breast-cancer/
- [x] https://www.mammotome.com/patient-resources/mammogram-guidelines/
- [x] https://www.mammotome.com/patient-resources/mammotome-breast-biopsy-devices/
- [x] https://www.mammotome.com/patient-resources/mri-breast-imaging/
- [x] https://www.mammotome.com/patient-resources/risk-factors/
- [x] https://www.mammotome.com/patient-resources/staging/
- [x] https://www.mammotome.com/patient-resources/treatment-options/
- [x] https://www.mammotome.com/patient-resources/types-of-breast-cancer/
- [x] https://www.mammotome.com/patient-resources/ultrasound-breast-imaging/
- [x] https://www.mammotome.com/patient-resources/understanding-mammograms/
- [x] https://www.mammotome.com/patient-resources/what-is-a-breast-biopsy/
- [x] https://www.mammotome.com/patient-resources/whos-who-on-my-treatment-team/
- [x] https://www.mammotome.com/patient-resources/your-pathology-report/
- [x] https://www.mammotome.com/portfolios/gamma-detection/
- [x] https://www.mammotome.com/portfolios/magnetic-lesion-localization/
- [x] https://www.mammotome.com/portfolios/magnetic-sentinel-lymph-node-biopsy/
- [x] https://www.mammotome.com/portfolios/mri/
- [x] https://www.mammotome.com/portfolios/stereotactic/
- [x] https://www.mammotome.com/portfolios/ultrasound/
- [x] https://www.mammotome.com/privacy-policy/
- [x] https://www.mammotome.com/product-and-technical-documents/
- [x] https://www.mammotome.com/product-thank-you/
- [x] https://www.mammotome.com/products-overview/ (moved to https://main--mammotome--hlxsites.hlx.page/us/en/products/)
- [x] https://www.mammotome.com/products/breast-biopsy-markers/
- [x] https://www.mammotome.com/products/breast-biopsy-markers/biomarc/
- [x] https://www.mammotome.com/products/breast-biopsy-markers/hydromark/
- [x] https://www.mammotome.com/products/breast-biopsy-markers/mammomark-cormark/
- [x] https://www.mammotome.com/products/breast-biopsy-markers/mammostar/
- [x] https://www.mammotome.com/products/magseed/
- [x] https://www.mammotome.com/products/magtrace/
- [x] https://www.mammotome.com/products/mammotome-confirm/
- [x] https://www.mammotome.com/products/mammotome-core-needles/
- [x] https://www.mammotome.com/products/mammotome-dualcore-system/
- [x] https://www.mammotome.com/products/mammotome-elite/
- [x] https://www.mammotome.com/products/mammotome-revolve/
- [x] https://www.mammotome.com/products/mammotome-revolve/mammotome-revolve-sterotactic/
- [x] https://www.mammotome.com/products/mammotome-revolve/mammotome-revolve-ultrasound/
- [x] https://www.mammotome.com/products/mammotome-st-ex-mr/mammotome-ex-biopsy-device/
- [x] https://www.mammotome.com/products/neoprobe/
- [x] https://www.mammotome.com/products/sentimag/
- [x] https://www.mammotome.com/products/supercore-instrument/
- [x] https://www.mammotome.com/products/tru-core-ii/
- [x] https://www.mammotome.com/products/xpert-40/
- [x] https://www.mammotome.com/red-doc-2/ (duplicate of https://main--mammotome--hlxsites.hlx.page/us/en/legal/conformity/red-doc)
- [x] https://www.mammotome.com/red-doc/ (created as https://main--mammotome--hlxsites.hlx.page/us/en/legal/conformity/red-doc)
- [x] https://www.mammotome.com/schedule-a-demo/ (page here: https://main--mammotome--hlxsites.hlx.page/us/en/schedule-a-demo)
- [x] https://www.mammotome.com/social-media-guidelines/ (page here: https://main--mammotome--hlxsites.hlx.page/us/en/social-media-guidelines)
- [x] https://www.mammotome.com/submit-a-tech-support-ticket/
- [x] https://www.mammotome.com/tag/brochure/ (Placeholder page: SKIP)
- [x] https://www.mammotome.com/technical-support/
- [x] https://www.mammotome.com/terms-conditions/
- [x] https://www.mammotome.com/thank-you-markers/ (same as normal thank you - found here: https://main--mammotome--hlxsites.hlx.live/us/en/thank-you/)
- [x] https://www.mammotome.com/thank-you-post-event/ (same as normal thank you - found here: https://main--mammotome--hlxsites.hlx.live/us/en/thank-you/)
- [x] https://www.mammotome.com/thank-you/ (same as normal thank you - found here: https://main--mammotome--hlxsites.hlx.live/us/en/thank-you/)
- [x] https://www.mammotome.com/tradeshow-thank-you/ (same as normal thank you - found here: https://main--mammotome--hlxsites.hlx.live/us/en/thank-you/)
- [x] https://www.mammotome.com/us-product-catalog/ (found here: https://main--mammotome--hlxsites.hlx.page/us/en/products/catalog-french-canada)

**Comment by karlpauls** [comment]
None reachable? 

- https://www.mammotome.com/portfolios/benign-lesion-localization/

**Comment by nsdere** [comment]
These links are also not reachable?:
- https://www.mammotome.com/about-us/our-culture/
- https://www.mammotome.com/confirm-submission/
- https://www.mammotome.com/contact/elementor-16435/
- https://www.mammotome.com/demo-thank-you/
- https://www.mammotome.com/healthcare-professionals-category/partner-with-mammotome/
- https://www.mammotome.com/healthcare-professionals-category/studies/
- https://www.mammotome.com/healthcare-professionals/placeholder-for-menus-and-categories/
- https://www.mammotome.com/hospital-marketing-kit-downloadable-assets/
- https://www.mammotome.com/hospital-marketing-kit-preview/
- https://www.mammotome.com/legal-imprint/
- https://www.mammotome.com/red-doc-2/
- https://www.mammotome.com/red-doc/
- https://www.mammotome.com/social-media-guidelines/
- https://www.mammotome.com/tag/brochure/

 And, "thank you" pages cannot be accessed through the navigation menu or the footer, but are likely displayed after submitting a form.
- https://www.mammotome.com/product-thank-you/
- https://www.mammotome.com/thank-you-markers/
- https://www.mammotome.com/thank-you-post-event/
- https://www.mammotome.com/thank-you/
- https://www.mammotome.com/tradeshow-thank-you/

**Comment by karlpauls** [comment]
That would be good, @nsdere lets keep listing invalid urls in comments and we remove them in the end.

**Comment by solaris007** [comment]
all form thank you pages should point to this as all are identical: https://main--mammotome--hlxsites.hlx.live/us/en/thank-you/

**Comment by dzehnder** [comment]
added https://www.mammotome.com/patient-resources-category/webinars/ to the list as it seems to have only dummy content

**Comment by karlpauls** [comment]
@krizel4, @kelseywilliams751, we imported the page listed in this issue - can you please review if you think that was all or if we missed something (notice, some mention that they where skipped so double check if that was correct)?

**Comment by kelseywilliams751** [comment]
I agree with most of the skipped pages, I'm not sure why most of them were created in the first place.

I've already created the two hospital marketing kit pages. Those are not linked on purpose. The intention is our sales reps will provide direct links to prospective customers and after sales are completed.

We intentionally created identical thank you pages with unique URLs for better conversion tracking. We wanted to easily and quickly identify which forms users filled out, particularly when tracking conversions in Google Analytics. For example /confirm-your-submission/ is used for our technical support, innovate, and investigator forms because we don't want to track these form fills as raw leads.

If we're only going to use one thank you page for all of our forms, including external landing pages built in Marketo, do you have a Google Analytics friendly solution for conversion tracking?

**Comment by solaris007** [comment]
@kelseywilliams751 we were not aware of the significance of individual thank you pages for GA. Feel free to simply copy the thank you page and create individual ones. @jalagari it seems we need the forms to use individual thank you pages. Could you kindly work with @kelseywilliams751 ?
