### ISSUE TITLE
Two Columns within a Card

### ISSUE THREAD

**Issue by kelseywilliams751** [hlxsites/mammotome#377]
I need to create a card with two columns that looks like this for the hospital marketing kit download page https://main--mammotome--hlxsites.hlx.page/us/en/hospital-marketing-kit-download-center

![Screenshot 2023-06-29 at 8 57 37 AM](https://github.com/hlxsites/mammotome/assets/110261213/29c9c710-664a-430e-a19d-a443a7d2c7fc)

The image uses about 20% of the card and the text uses about 80% of the card. There are several download links in the card, so the entire card should not be clickable. I do not need the divider line under the header.

I'm not sure if the solution is a card variation or a column variation. There is already a "image cards" style for columns that displays the image like a card, but not the text.

**Comment by solaris007** [comment]
@kelseywilliams751 is this something you need before the US-en go-live? If no, we could push it for right after go-live and you could use an alternate arrangement until then.

**Comment by kelseywilliams751** [comment]
I can work with the columns layout temporarily. But will want to resolve this soon after go-live.

**Comment by solaris007** [comment]
@dzehnder since go-live moves by a week, would you have time to implement this? should not be dramatic :)
