### ISSUE TITLE
Import Languages: DE, ES, FR, IT, PL, UK

### ISSUE THREAD

**Issue by solaris007** [hlxsites/mammotome#395]
Using the recently merged importer config, please import the rest of the languages.

- [x] Import DE, ES, FR, IT, PL, UK
- [x] Manual reconstitution of content where necessary (see https://cq-dev.slack.com/archives/C04TVNL3S3W/p1688376060437479?thread_ts=1688374836.504829&cid=C04TVNL3S3W)
- [x] Internal QA

**Comment by karlpauls** [comment]
DE urls to check:

- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/footer
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/ifu-index
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/kontakt
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/legal-imprint
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/nav
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/portfolios/gammadetektion
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/portfolios/mrt
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/portfolios/stereotaxie
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/portfolios/ultraschall
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/product-support
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/product-support-template
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/products/breast-biopsy-markers
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/products/mammotome-brustbiopsiemarker/
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/products/mammotome-brustbiopsiemarker/hydromark
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/products/mammotome-brustbiopsiemarker/mammomark-cormark
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/products/mammotome-brustbiopsiemarker/mammostar
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/products/mammotome-confirm
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/products/mammotome-elite
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/products/mammotome-revolve/
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/products/mammotome-revolve/mammotome-revolve-stereotaxie
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/products/mammotome-revolve/mammotome-revolve-ultraschall
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/products/neoprobe
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/products/tru-core-ii
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/products/xpert-40
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/rechtliches-california-consumer-privacy-act
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/rechtliches-datenschutzrichtlinie
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/rechtliches-geschaeftsbedingungen
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/rechtliches-online-nutzungsbedingungen
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/rechtliches-urheberrecht-marke
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/ueber-uns-unsere-geschichte/
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/ueber-uns-unsere-geschichte/karriere
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/ueber-uns-unsere-geschichte/standorte
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/ueber-uns-unsere-geschichte/team
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/ueber-uns-unsere-geschichte/unsere-geschichte
- [ ] https://main--mammotome--hlxsites.hlx.page/de/de/uebersicht-portfolios

**Comment by karlpauls** [comment]
ES urls to check:

- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/contacto
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/descripcion-productos
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/footer
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/healthcare-professionals
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/healthcare-professionals-category/eventos-comerciales
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/healthcare-professionals-category/evidencias-clinicas
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/healthcare-professionals-category/seminarios-practicos
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/healthcare-professionals-category/webinars
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/legal-condiciones-de-uso-en-linea
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/legal-copyright-marca-comercial
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/legal-politica-de-privacidad
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/nav
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/patient-resources
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/patient-resources-category/biopsia-de-mama
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/patient-resources-category/comprender-los-resultados-de-la-biopsia
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/patient-resources-category/cuidado-de-los-senos
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/patient-resources-category/dispositivos-de-biopsia-mammotome
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/portfolios/biopsia-magnetica-de-ganglio-linfatico-centinela
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/portfolios/deteccion-gamma
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/portfolios/estereotactica
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/portfolios/rm
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/portfolios/ultrasonido
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/product-support
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/products/breast-biopsy-markers
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/products/mammotome-confirm
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/products/mammotome-elite
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/products/mammotome-revolve
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/products/mammotome-revolve/mammotome-revolve-u-s
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/products/marcadores-para-biopsia-de-mama-mammotome
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/products/marcadores-para-biopsia-de-mama-mammotome/biomarc
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/products/marcadores-para-biopsia-de-mama-mammotome/hydromark
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/products/marcadores-para-biopsia-de-mama-mammotome/mammomark-y-cormark
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/products/marcadores-para-biopsia-de-mama-mammotome/mammostar
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/products/neoprobe
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/products/tru-core-ii
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/products/xpert-40
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/sobre-nosotros-nuestra-historia
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/sobre-nosotros-nuestra-historia/equipo
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/sobre-nosotros-nuestra-historia/nuestra-historia
- [ ] https://main--mammotome--hlxsites.hlx.page/es/es/sobre-nosotros-nuestra-historia/ubicaciones

**Comment by karlpauls** [comment]
FR urls to check:
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/a-propos-de-nous-notre-histoire
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/a-propos-de-nous-notre-histoire/equipe
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/a-propos-de-nous-notre-histoire/notre-histoire
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/a-propos-de-nous-notre-histoire/sites
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/contact
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/footer
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/index-mode-demploi
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/legal-imprint
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/mentions-legales-california-consumer-privacy-act
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/mentions-legales-conditions-dutilisation-en-ligne
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/mentions-legales-droit-dauteur-marque-deposee
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/mentions-legales-politique-de-confidentialite
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/nav
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/panorama-solutions
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/portfolios/detection-des-rayons-gamma
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/portfolios/irm
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/portfolios/stereotaxique
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/portfolios/ultrason
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/presentation-produits
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/product-support
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/product-support-template
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/products/breast-biopsy-markers
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/products/mammotome-confirm
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/products/mammotome-elite
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/products/mammotome-revolve
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/products/mammotome-revolve/mammotome-revolve-stereotaxique
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/products/mammotome-revolve/mammotome-revolve-ultrasons
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/products/marqueurs-de-biopsie-mammaire
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/products/marqueurs-de-biopsie-mammaire/hydromark
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/products/marqueurs-de-biopsie-mammaire/mammomark-cormark
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/products/marqueurs-de-biopsie-mammaire/mammostar
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/products/neoprobe
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/products/tru-core-ii
- [ ] https://main--mammotome--hlxsites.hlx.page/fr/fr/products/xpert-40

**Comment by karlpauls** [comment]
IT urls to check:
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/chi-siamo-la-nostra-storia
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/chi-siamo-la-nostra-storia/la-nostra-storia
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/chi-siamo-la-nostra-storia/opportunita-di-carriera
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/chi-siamo-la-nostra-storia/sedi
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/chi-siamo-la-nostra-storia/team
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/footer
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/indice-delle-istruzioni-per-luso
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/informazioni-legali-california-consumer-privacy-act
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/informazioni-legali-condizioni-di-utilizzo-del-sito-web
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/informazioni-legali-copyright-marchi-registrati
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/informazioni-legali-informativa-sulla-privacy
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/legal-imprint
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/nav
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/portfolios/guida-ecografica
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/portfolios/rilevamento-di-radiazioni-gamma
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/portfolios/rm
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/portfolios/stereotassi
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/product-support
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/product-support-template
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/products/dispositivo-per-biopsia-mammotome-ex
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/products/dispositivo-per-biopsia-mammotome-rm
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/products/dispositivo-per-biopsia-mammotome-st
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/products/mammotome-confirm
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/products/mammotome-elite
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/products/mammotome-revolve
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/products/mammotome-revolve/mammotome-revolve-per-biopsie-stereotassiche
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/products/mammotome-revolve/mammotome-revolve-u-s
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/products/marcatori-per-biopsia-della-mammella-mammotome
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/products/marcatori-per-biopsia-della-mammella-mammotome/hydromark
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/products/marcatori-per-biopsia-della-mammella-mammotome/mammomark-cormark
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/products/marcatori-per-biopsia-della-mammella-mammotome/mammostar
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/products/neoprobe
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/products/tru-core-ii
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/products/xpert-40
- [ ] https://main--mammotome--hlxsites.hlx.page/it/it/referente

**Comment by karlpauls** [comment]
PL urls to check:
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/footer
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/indeks-instrukcji-obslugi
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/kontakt
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/legal-imprint
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/nav
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/nota-prawna-california-consumer-privacy-act
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/nota-prawna-polityka-prywatnosci
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/nota-prawna-prawa-autorskie-i-znaki-towarowe
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/nota-prawna-warunki-korzystania-online
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/o-nas-nasza-historia
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/o-nas-nasza-historia/lokalizacje
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/o-nas-nasza-historia/nasza-historia
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/o-nas-nasza-historia/zespol
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/portfolios/detekcja-promieniowania-gamma
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/portfolios/mri
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/portfolios/stereotaktyczna-biopsja-piersi
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/portfolios/ultrasonografia
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/product-support
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/product-support-template
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/products/mammotome-confirm
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/products/mammotome-elite
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/products/mammotome-revolve
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/products/mammotome-revolve/mammotome-revolve-stereotactic
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/products/mammotome-revolve/mammotome-revolve-ultrasound
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/products/neoprobe
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/products/revolve-ex
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/products/tru-core-ii
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/products/xpert-40
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/products/znaczniki-po-biopsji-piersi-firmy-mammotome
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/products/znaczniki-po-biopsji-piersi-firmy-mammotome/hydromark
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/products/znaczniki-po-biopsji-piersi-firmy-mammotome/mammomark-i-cormark
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/products/znaczniki-po-biopsji-piersi-firmy-mammotome/mammostar
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/przeglad-portfolio
- [ ] https://main--mammotome--hlxsites.hlx.page/pl/pl/przeglad-produkty

**Comment by karlpauls** [comment]
UK urls to check:
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/about-us-our-story
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/about-us-our-story/locations
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/about-us-our-story/our-history
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/about-us-our-story/team
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/contact
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/emea-distribution-product-catalog
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/emea-product-catalog
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/footer
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/ifu-index
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/legal-california-consumer-privacy-act
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/legal-copyright-trademark
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/legal-imprint
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/legal-online-terms-of-use
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/legal-privacy-policy
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/legal-terms-conditions
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/nav
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/news-media
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/news-media/mammotome-launches-the-first-vacuum-assisted-breast-biopsy-system-designed-for-lesion-excision
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/portfolios
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/portfolios/gamma-detection
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/portfolios/mri
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/portfolios/stereotactic
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/portfolios/ultrasound
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/product-support
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/product-support-template
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/products/mammotome-elite
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/products/mammotome-revolve/mammotome-revolve-stereotactic
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/products/mammotome-revolve/mammotome-revolve-ultrasound
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/products/mammotomes-breast-biopsy-markers
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/products/mammotomes-breast-biopsy-markers/hydromark
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/products/mammotomes-breast-biopsy-markers/mammomark-cormark
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/products/mammotomes-breast-biopsy-markers/mammostar
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/products/neoprobe
- [ ] https://main--mammotome--hlxsites.hlx.page/uk/en/products/xpert-40

**Comment by karlpauls** [comment]
The import is done. I think we should separate the QA as that is a global topic.
