### ISSUE TITLE
Clinical Evidence Links: target=_blank

### ISSUE THREAD

**Issue by krizel4** [hlxsites/mammotome#416]
URLs that link to pdfs should open a new window.

re: https://main--mammotome--hlxsites.hlx.page/us/en/healthcare-professionals/clinical-evidence

**Comment by solaris007** [comment]
franklin discussion regarding link targeting: https://cq-dev.slack.com/archives/C9KD0TT6G/p1663656906871009

@dzehnder i think we should auto-infer the target without author involvement.
