### ISSUE TITLE
Add new metadata for button widths

### ISSUE THREAD

**Issue by krizel4** [hlxsites/mammotome#425]
Can we add a styling option for buttons to occupy the width of the container (like the products page, screenshot below for ref)

![image](https://github.com/hlxsites/mammotome/assets/55035633/63e8ffd8-a04b-4f6a-9881-ec61fbe6d014)

<img width="930" alt="image" src="https://github.com/hlxsites/mammotome/assets/55035633/bd509ce0-371c-4c7a-b615-e55767f642ab">

**Comment by Acidham** [comment]
@krizel4 Please review if this fits your expectation: https://425-metadata-for-button-widths--mammotome--hlxsites.hlx.page/us/en/technical-support

The documentation can be found here: https://github.com/hlxsites/mammotome/blob/425-metadata-for-button-widths/docs/section-metadata.md#button-width

**Comment by krizel4** [comment]
@Acidham this looks great. Thank you!

**Comment by Acidham** [comment]
Great thx...we will merge into `main` then
