### ISSUE TITLE
Product Reference Buttons have Incorrect Links

### ISSUE THREAD

**Issue by kelseywilliams751** [hlxsites/mammotome#427]
The buttons built into the product reference section have incorrect links on select product pages

Affected pages are:
https://main--mammotome--hlxsites.hlx.page/us/en/products/breast-biopsy-markers/biomarc
https://main--mammotome--hlxsites.hlx.page/us/en/products/breast-biopsy-markers/hydromark
https://main--mammotome--hlxsites.hlx.page/us/en/products/breast-biopsy-markers/
https://main--mammotome--hlxsites.hlx.page/us/en/products/breast-biopsy-markers/mammomark-comark
https://main--mammotome--hlxsites.hlx.page/us/en/products/breast-biopsy-markers/mammostar

Request information button linking to: https://main--mammotome--hlxsites.hlx.page/us/en/products/contact/ (404 error) instead of https://main--mammotome--hlxsites.hlx.page/us/en/contact/
Product Support button linking to: https://main--mammotome--hlxsites.hlx.page/us/en/products/product-support (404 error) instead of https://main--mammotome--hlxsites.hlx.page/us/en/product-support
Product Document buttons working correctly.

The URLs have /products/ that shouldn't be there.

**Comment by karlpauls** [comment]
@kelseywilliams751 - good catch! The urls for these are configurable via the placeholders excel but I forgot to set that up for the default language (i.e., us/en). That is done now, however, that uncovered a bug in the product reference which is fixed via #429 

Thanks for reporting!
