### ISSUE TITLE
Blue button hero header: IT, SP, PL

### ISSUE THREAD

**Issue by krizel4** [hlxsites/mammotome#442]
For the Italian, Spanish and Polish website, the button appears blue instead of the transparent outlined button.

<img width="839" alt="image" src="https://github.com/hlxsites/mammotome/assets/55035633/4fac70dc-99be-4078-a388-ed5f84ac98e6">

**Comment by karlpauls** [comment]
@krizel4, that is actual fixable in the content. I fixed it for the index pages - thanks for reporting!
