### ISSUE TITLE
PL Text

### ISSUE THREAD

**Issue by krizel4** [hlxsites/mammotome#443]
Some of the text is bold when it shouldn't be. 

<img width="657" alt="image" src="https://github.com/hlxsites/mammotome/assets/55035633/241d9fde-33d7-472b-aaf8-bf464c930e7d">

**Comment by karlpauls** [comment]
@krizel4 , yes, I noticed that too today - I think it is technically not bold. My guess is that the font we use is missing some glyphs and it falls back to the system font for those. That is why it is happening only for PL. I'll look into the font tomorrow - please ignore the arbitrary "boldness" in PL for the time being.
