### ISSUE TITLE
Metadata Request

### ISSUE THREAD

**Issue by krizel4** [hlxsites/mammotome#462]
Can we add an option for header-colored-secondary?

https://www.mammotome.com/product-support/
https://www.mammotome.com/technical-support/

Designers sometimes create blue headers for content. 

The blue should be #5F8DDA

**Comment by Acidham** [comment]
![image](https://github.com/hlxsites/mammotome/assets/17712121/3f86ab66-4190-48ff-92ec-33932d7e62c3)
