### ISSUE TITLE
ES: Product Support Template

### ISSUE THREAD

**Issue by krizel4** [hlxsites/mammotome#463]
Link: https://main--mammotome--hlxsites.hlx.live/es/es/product-support/tru-core-ii-automatic-core-biopsy-instrument

**Order should be:**
- DOCUMENTOS DEL PRODUCTO
header-wide, header-colored, header-uppercased
- Product Name
- Product Image

**Franklin:** 
<img width="854" alt="image" src="https://github.com/hlxsites/mammotome/assets/55035633/f52732e7-c4c6-4b56-ad78-ef16e3f03619">

**Original:** 
<img width="786" alt="image" src="https://github.com/hlxsites/mammotome/assets/55035633/4f435352-e9a9-474a-9449-0bb93d7f86ec">

**Comment by karlpauls** [comment]
Should be done now. This is possible to be edited via the content (i.e., the product-support-template plus the placeholders). 

However, @krizel4, I'm not sure why the product support template for ES is different from all others - it seems like it would make sense to have it be the same.

**Comment by karlpauls** [comment]
Please notice: the link in this issue was against .live - the change I made is visible on .page for now. I.e.:

https://main--mammotome--hlxsites.hlx.page/es/es/product-support/tru-core-ii-automatic-core-biopsy-instrument

should look ok now.
