### ISSUE TITLE
"Waiting Label" for Form: FR/IT/DE/PL

### ISSUE THREAD

**Issue by krizel4** [hlxsites/mammotome#474]
Waiting labels are needed for the other language contact forms:

**Italian**: Attendi
**French**: Veuillez patienter
**German**: Bitte warten
**Polish**: Proszę czekać

**Comment by jalagari** [comment]
We are updating but you can follow same steps mentioned in https://github.com/hlxsites/mammotome/issues/476#issuecomment-1635291394 for future updates
