### ISSUE TITLE
Update default value for Form Name for other languages

### ISSUE THREAD

**Issue by krizel4** [hlxsites/mammotome#475]
**Form Name**

- **English Global:** [EN-UK] main contact form
- **German**: [DE] main contact form
- **Italian**: [IT] main contact form
- **Polish**: [PL] main contact form
- **Spanish**: [ES] main contact form
- **French**: [FR] main contact form

**Comment by jalagari** [comment]
We are updating but you can follow same steps mentioned in https://github.com/hlxsites/mammotome/issues/476#issuecomment-1635291394 for future updates
