### ISSUE TITLE
Remove Default Country for Each Form

### ISSUE THREAD

**Issue by krizel4** [hlxsites/mammotome#476]
I noticed that each form defaults to a country that doesn't quite make sense. 

Instead, can we have a "Select" placeholder?

**French:**  Choisir
**German:** Bitten wählen Sie
**Italian:** Seleziona
**Polish:** Wybierz
**English EU:** Select

For the English - North American site, "United States" could remain at the top. But for all the other forms, United States can sit alphabetically within the list.

<img width="758" alt="image" src="https://github.com/hlxsites/mammotome/assets/55035633/fc55a4bf-94db-451f-8a86-217464c0f0e5">

<img width="760" alt="image" src="https://github.com/hlxsites/mammotome/assets/55035633/190c5632-2cc0-4870-a16d-fba6640e59b2">

<img width="710" alt="image" src="https://github.com/hlxsites/mammotome/assets/55035633/046f5dc1-c3cc-40db-a8c3-d032f6322fcd">

<img width="776" alt="image" src="https://github.com/hlxsites/mammotome/assets/55035633/9936f20d-0c73-4c50-b04c-c47fe1cb506a">

<img width="688" alt="image" src="https://github.com/hlxsites/mammotome/assets/55035633/297680c3-0a2d-4ffe-9299-f3d909a509b9">

**Comment by jalagari** [comment]
@krizel4 - This can be easily controllable by the author by following this steps.

- Goto Excel file, Select sheet based on language.
- In country row and value column just change value which need to be set as default,

We are updating excel now but feel free to trying it for future changes.
