### ISSUE TITLE
Allow Custom Anchor Links in Product Database

### ISSUE THREAD

**Issue by krizel4** [hlxsites/mammotome#485]
https://main--mammotome--hlxsites.hlx.page/us/en/products/breast-biopsy-markers/

"Request Information" should scroll down to "Learn More About Mammotome® Markers" form.

Please use a smooth scroll. Thanks!

**Comment by solaris007** [comment]
@krizel4 - as per design discussed, the product reference block is generic and currently does not have the capability of adapting the "Request Information" link for a single page. If we were to introduce an enhancement of a single page override, how would you as the business practitioner like to author it? on the page as a property of the reference block table, in the product database, or anything else?

**Comment by krizel4** [comment]
@solaris007, it's a feature we're testing on the markers page. If all goes well, we'd implement it for all pages. but we still need to continue testing. i think for now it may be best referenced in the product database.

**Comment by solaris007** [comment]
@dzehnder please take a look

**Comment by dzehnder** [comment]
@krizel4, I started implementing the improvement. You can test it here: https://485-anchor-link--mammotome--hlxsites.hlx.page/us/en/products/breast-biopsy-markers/

To link the form on a product basis, I introduced an additional column in the product database called `Information`. You can link the heading from the form there. Is this how you would imagine it? Or would you like to link it differently in the product database?
