### ISSUE TITLE
Implement Product Carousel

### ISSUE THREAD

**Issue by solaris007** [hlxsites/mammotome#530]
As per design:
![Screenshot 2023-08-08 at 15 54 07](https://github.com/hlxsites/mammotome/assets/1872195/5385643f-ce0f-48a9-82a6-8e29fb40fac8)

Discuss with customer the UX flow (slide to one next card, slide three next, ...)

**Comment by Acidham** [comment]
Mobile Mock:
![image (2)](https://github.com/hlxsites/mammotome/assets/17712121/bfc7645f-7da6-46f3-9121-9453b66d0684)
