### ISSUE TITLE
404 on French Mammotome Elite Product Documents Page

### ISSUE THREAD

**Issue by kelseywilliams751** [hlxsites/mammotome#555]
We're seeing a 404 for this URL:
https://www.mammotome.com/fr/fr/product-support/mammotome-elite

Here's the preview URL:
https://main--mammotome--hlxsites.hlx.page/fr/fr/product-support/mammotome-elite

I thought maybe the page hadn't been published somehow, but I'm unable to publish the page. I'm assuming I can't publish the page because it is generated by the products.xlsx

The preview page looks as it should, so I'm unclear why we're getting a 404 on production.

Looping in @SwethaPasala who manages the EMEA sites

**Comment by Acidham** [comment]
@kelseywilliams751 `product.xlsx` row number 12 is the `mammotome-elite` entry, correct? Was the product.xlsx published?

**Comment by Acidham** [comment]
@kelseywilliams751 I found the issue: `/fr/fr/product-support-template.docx` was not published and therefore all the support doc pages in `fr` were not accessible.

**Comment by kelseywilliams751** [comment]
Thank you! The page is working on our end too!
