### ISSUE TITLE
Fallback font for titles and bold texts

### ISSUE THREAD

**Issue by chicharr** [hlxsites/mammotome#65]
Currently there is a fallback font `robotoflex-regular-normal-400-fallback`configured as a fallback for "Roboto".  The fallback font works very well for normal text, however it doesn't honour the `font-weight` argument.
The consequence of this is that titles `h1`, `h2`, etc... and bold texts, are first rendered with the normal `font-weight` and when the fallback font is swapped by the actual one, the right `font-weight` is applied causing CLS.

This ticket is to investigate if there is a way to apply font-weight to the fallback-font

**Comment by solaris007** [comment]
@dzehnder let's do this to boost performance with go-live pushed by a week - please talk to @karlpauls who has recently modified fallback font handling.

**Comment by solaris007** [comment]
take note of https://github.com/adobe/helix-project-boilerplate/commit/e6399b8eed912d23f298b2ea8881a584378d4a64

**Comment by solaris007** [comment]
@dzehnder please take a look at this. Font swapping is still a contributor to CLS (around 0.002+). it would be awesome if we found a better solution (see previous comment). Might require some experimentation. @karlpauls recently switched to pure CSS fonts, but given the solution by uncled it might be beneficial to go back to woff2. Let me know your thoughts.
