### ISSUE TITLE
Current language not represented in language switcher

### ISSUE THREAD

**Issue by dzehnder** [hlxsites/mammotome#77]
When switching the language to something other than English, the language switcher should show the selected language on top and move the previous language into the dropdown.

Current behaviour:
![Screenshot 2023-04-28 at 15 03 09](https://user-images.githubusercontent.com/16799758/235155196-cbe7bfab-e0b3-4db0-91da-57ceed878d26.png)

**Comment by Acidham** [comment]
will be fixed within #16
