### ISSUE TITLE
Hero image block

### ISSUE THREAD

**Issue by dzehnder** [hlxsites/mammotome#81]
Items summarized from all comments:
- [x] Include `h2` element for auto blocking
- [x] Make the gradient overlay adjustable
- [x] Increase block height to match the one on the original page
- [x] Adjust image crop to match the one on the original page

---

A lot of pages contain a hero image with white text and sometimes a button.
There is always a gradient overlay with different colors.
All hero images have the same cutout, currently achieved with an svg overlay image.

Index page:
![Screenshot 2023-04-28 at 15 55 01](https://user-images.githubusercontent.com/16799758/235166992-66a66cd3-207a-49cd-aea5-51cf9ef31cca.png)

Other pages:
![Screenshot 2023-04-28 at 15 55 11](https://user-images.githubusercontent.com/16799758/235167036-e9ccc05c-949d-4ddb-bc78-a72e7a86b1f8.png)

**Comment by solaris007** [comment]
is this not done via #23 ?

**Comment by dzehnder** [comment]
@solaris007 curretly only works if there is an `h1` following the hero image. This is not the case for the index page. So we either adjust the `h1` font for the index page, or we adjust the autoblocking creation for the hero block.

Also, the background color is currently the same on all hero blocks. On the page they are different some times, most noticeable on the index page

**Comment by solaris007** [comment]
@dzehnder thanks for elaborating, i advocate for auto-blocking adjustment, WDYT?

**Comment by dzehnder** [comment]
@solaris007 Agreed, seems more intuitive for the author IMO.

Also just noticed, for the auto blocking, we need to include the first link after a heading into the hero block and make it appear like a button (see index page -> our solutions)

**Comment by dzehnder** [comment]
Couple more things I noticed:
Height difference: block should be slightly higher (increase padding/margin of the font).
Due to this, the image crop is different. Additionally, the image alignment might need to be adjusted.
See difference:
![Screenshot 2023-05-04 at 10 24 21](https://user-images.githubusercontent.com/16799758/236149934-50325463-eb58-452f-b657-7ab7f4b010b1.png)
![Screenshot 2023-05-04 at 10 24 29](https://user-images.githubusercontent.com/16799758/236149958-74e1a854-505b-4333-89ec-ecaac34ce589.png)
