### ISSUE TITLE
Contact us block

### ISSUE THREAD

**Issue by dzehnder** [hlxsites/mammotome#82]
Items to implement:

- [ ] h1 font invert
- [ ] be able to center content
- [ ] increase padding at the bottom and top

---

Almost all pages have a contact us block with a background image and a round cutout:

![Screenshot 2023-04-28 at 16 02 32](https://user-images.githubusercontent.com/16799758/235168941-f31355a8-c5ee-4751-bbcb-484bc95e5143.png)

**Comment by solaris007** [comment]
this should be possible using the feature implemented in #40 - can you verify?

**Comment by dzehnder** [comment]
There are a couple things missing:
* `h1` font invert
* center content
* increase padding at the bottom

currently looks like this:
![Screenshot 2023-05-03 at 14 26 15](https://user-images.githubusercontent.com/16799758/235915095-bcd1929f-76a1-48b9-8b6b-bf4e599d8d66.png)
