### ISSUE TITLE
YouTube player embed

### ISSUE THREAD

**Issue by dzehnder** [hlxsites/mammotome#87]
Some pages contain an embedded YouTube video.
The embedded video shows a thumbnail with a play button (not the YouTube version). As soon as the video is clicked, the YouTube Iframe with the video opens.
Maybe the embed bock could be used with slight modifications: https://www.hlx.live/developer/block-collection/embed

There are two versions.
Single embedded video:
https://www.mammotome.com/portfolios/magnetic-lesion-localization/

https://user-images.githubusercontent.com/16799758/235608879-bd44c32a-05a2-4118-befe-e2326d656ef0.mov

Multiple embedded videos:
https://www.mammotome.com/portfolios/stereotactic/

![Screenshot 2023-05-02 at 09 45 13](https://user-images.githubusercontent.com/16799758/235608860-9a09eb1b-1162-49d1-85e4-47722a72272c.png)

**Comment by solaris007** [comment]
@dzehnder this was implemented as part of #25 no?
