### ISSUE TITLE
Timeline block

### ISSUE THREAD

**Issue by dzehnder** [hlxsites/mammotome#88]
The "Our History" Page contains a vertical timeline view of different milestones.
When the user scrolls, the timeline items above the center of the screen change their background color:
https://www.mammotome.com/about-us/our-history/

https://user-images.githubusercontent.com/16799758/235611329-b910e59f-0064-4da8-ab9b-d56d156a22fc.mov

**Comment by solaris007** [comment]
this was implemented as part of #18
