### ISSUE TITLE
Form block

### ISSUE THREAD

**Issue by dzehnder** [hlxsites/mammotome#89]
There are two forms on the page, that could be combined into one block from a styling pov.
For other styled forms, see #90.
Functionally they are not very different, except that one has a file upload.

The page About Us > Innovate with Mammotome (https://www.mammotome.com/contact/innovate-with-mammotome/) contains a form to submit new innovations:
![Screenshot 2023-05-02 at 10 12 08](https://user-images.githubusercontent.com/16799758/235614123-ac2ae6d3-9124-41c8-894e-f31e319f50fc.png)

The page About Us > Investigator Initiated Study Request (https://www.mammotome.com/contact/investigator-initiated-study-request/) has a form, split into multiple sections and at the end is a file uploader, for multiple files.
![Screenshot 2023-05-02 at 10 48 35](https://user-images.githubusercontent.com/16799758/235621700-c267bbc5-91c5-4e9a-9544-e957dab6a090.png)

**Comment by solaris007** [comment]
we agreed with the customer to use a single style cc @jalagari
