### ISSUE TITLE
Form block alternate styling

### ISSUE THREAD

**Issue by dzehnder** [hlxsites/mammotome#90]
The "Contact Us, "schedule a demo" and "technical inquiry" forms have a different styling than the ones mentioned in #89.
Since the layout seems to be the same, only the font and the backgrund needs to be changed.
This could be achieved by introducing additional classes to the block (added in brackets in the first column)

Contact Us Form: https://www.mammotome.com/contact/
![Screenshot 2023-05-02 at 11 05 24](https://user-images.githubusercontent.com/16799758/235625651-239ca2a4-7ead-462a-a07f-0350db27834a.png)

Schedule a Demo Form: https://www.mammotome.com/schedule-a-demo/
![Screenshot 2023-05-02 at 11 05 49](https://user-images.githubusercontent.com/16799758/235625727-56fab3a9-15d0-4434-829c-7583c3e0573c.png)

Technical Inquiry Form: https://www.mammotome.com/submit-a-tech-support-ticket/
![Screenshot 2023-05-02 at 11 09 36](https://user-images.githubusercontent.com/16799758/235626439-b4165994-c548-4273-87bb-de461c2531b2.png)

**Comment by solaris007** [comment]
we agreed with the customer to use a single style cc @jalagari
