### ISSUE TITLE
Collapsible Block

### ISSUE THREAD

**Issue by dzehnder** [hlxsites/mammotome#91]
The FAQ Page has collapsible items.
When a user clicks the item, it opens.
It is only closed when the same item is clicked again.
https://www.mammotome.com/patient-resources/faqs-about-the-devices/

https://user-images.githubusercontent.com/16799758/235628105-261e22c0-d1c6-4167-94f9-eb78d73ce92e.mov

**Comment by solaris007** [comment]
@dzehnder @smiroslav can we use autoblocking here or section metadata? or do you envision a separate block? mind, the developer would structure everything in a block, whereas the author would probably not use a table for this. what is your stance and what are the options?

**Comment by dzehnder** [comment]
Not sure how we could use auto blocking in this case. How could the author define, what is being hidden and what not?
Same for section metadata IMO. Using a table (separate block) might be more intuitive, but open to other suggestions.

**Comment by smiroslav** [comment]
[PR](https://github.com/hlxsites/mammotome/pull/125) has been merged.
